/*
 * Author   : Ahmed Mohamed Aboud
 * Linkedin :https://www.linkedin.com/in/ahmed-mohamed-aboud-33b2471b1/
 * File Name: TIMER_Program.c
 * Date: 29 Dec 2023
 */

#include "../DIO/STD_Types.h"
#include "../DIO/bitmath.h"

#include "../DIO/DIO_Interface.h"
#include "../General_Interrupts/GEN_INTERRUPT__Interacing.h"

#include "TIMER_Reg.h"
#include "TIMER_CFG.h"
#include "TIMER_Private.h"
#include "TIMER_Interface.h"


void TIMER0_init(void)
{
	/*Operation Modes*/
#if (TIMER0_WAVE_GEN_MODE == TIMER0_NORMAL)
	CLEAR_BIT(TCCR0,TCCR_WGM00);
	CLEAR_BIT(TCCR0,TCCR_WGM01);
	SET_BIT(TCCR0,TCCR_FOC0);

#elif (TIMER0_WAVE_GEN_MODE == TIMER0_CTC)
	CLEAR_BIT(TCCR0,TCCR_WGM00);
	SET_BIT(TCCR0,TCCR_WGM01);
	//SET_BIT(TCCR0,TCCR_FOC0);
	OCR0 = OCR_TICK_NUMS;

#elif (TIMER0_WAVE_GEN_MODE == TIMER0_PWN_FAST)
	SET_BIT(TCCR0,TCCR_WGM00);
	SET_BIT(TCCR0,TCCR_WGM01);
	CLEAR_BIT(TCCR0,TCCR_FOC0);
	OCR0 = OCR_COMP_VALUE;

#elif (TIMER0_WAVE_GEN_MODE == TIMER0_PWM_PC)
	SET_BIT(TCCR0,TCCR_WGM00);
	CLEAR_BIT(TCCR0,TCCR_WGM01);
	CLEAR_BIT(TCCR0,TCCR_FOC0);
	OCR0 = OCR_COMP_VALUE;

#else
#error "WRONG OPERATION MODE CONFIGURATION"
#endif


	/*COMPARE MODE*/
#if (TIMER0_WAVE_GEN_MODE == TIMER0_PWN_FAST)

#if (TIMER0_COMPARE_MATCH_MODE_F_PWM == TIMER0_COMP_NORMAL_F_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM00);
	CLEAR_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_F_PWM == TIMER0_COMP_CLEAR_F_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_F_PWM == TIMER0_COMP_SET_F_PWM)
	SET_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#else
#error "WRONG OPERATION MODE CONFIGURATION"
#endif

#elif (TIMER0_WAVE_GEN_MODE == TIMER0_PWM_PC)

#if (TIMER0_COMPARE_MATCH_MODE_PC_PWM == TIMER0_COMP_NORMAL_NO_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM00);
	CLEAR_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_PC_PWM == TIMER0_COMP_CLEAR_PC_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_PC_PWM == TIMER0_COMP_SET_PC_PWM)
	SET_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#else
#error "WRONG OPERATION MODE CONFIGURATION"
#endif

#elif ((TIMER0_WAVE_GEN_MODE == TIMER0_CTC) || (TIMER0_WAVE_GEN_MODE == TIMER0_NORMAL))

#if (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_NORMAL_NO_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM00);
	CLEAR_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_TOGGLE_NO_PWM)
	SET_BIT(TCCR0,TCCR_COM00);
	CLEAR_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_CLEAR_NO_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_SET_NO_PWM)
	SET_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#endif

#else
#error "WRONG OPERATION MODE CONFIGURATION"
#endif


	/*Pre-select Configurations*/
	TCCR0 &= 0b11111000;
	TCCR0 |= CLOCK_CYCLE_SELECTED;
	DIO_setPinDirection(DIO_PORTB,PIN3,OUTPUT);
	TCNT0 = 0x00;
}

void TIMER0_normal(void)
{
	/* Wave Generation */
	CLEAR_BIT(TCCR0,TCCR_WGM00);
	CLEAR_BIT(TCCR0,TCCR_WGM01);
	SET_BIT(TCCR0,TCCR_FOC0);

#if (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_NORMAL_NO_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM01);
	CLEAR_BIT(TCCR0,TCCR_COM00);

#elif (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_TOGGLE_NO_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM01);
	SET_BIT(TCCR0,TCCR_COM00);

#elif (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_CLEAR_NO_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_SET_NO_PWM)
	SET_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#else
#error "WRONG CONFIGURATIONS !!"
#endif

	/* Pre-Scaling Configuration */
	TCCR0 &= 0b11111000;
	TCCR0 |= PRESCALING_1024_MASK;

#if (TIMER0_COMPARE_MATCH_MODE_NO_PWM != TIMER0_COMP_NORMAL_NO_PWM)
	DIO_setPinDirection(DIO_PORTB,PIN3,OUTPUT);
#endif
}

void TIMER0_CTC_(uint8 copy_upper_limit)
{
	/* Wave Generation */
	CLEAR_BIT(TCCR0,TCCR_WGM00);
	SET_BIT(TCCR0,TCCR_WGM01);
	SET_BIT(TCCR0,TCCR_FOC0);
	OCR0 = copy_upper_limit;

#if (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMPARE_MATCH_MODE_NO_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM01);
	CLEAR_BIT(TCCR0,TCCR_COM00);

#elif (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_TOGGLE_NO_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM01);
	SET_BIT(TCCR0,TCCR_COM00);

#elif (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_CLEAR_NO_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_NO_PWM == TIMER0_COMP_SET_NO_PWM)
	SET_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#else
#error "WRONG CONFIGURATIONS !!"
#endif

	/* Pre-Scaling Configuration */
	TCCR0 &= 0b11111000;
	TCCR0 |= PRESCALING_1024_MASK;

#if (TIMER0_COMPARE_MATCH_MODE_NO_PWM != TIMER0_COMP_NORMAL_NO_PWM)
	DIO_setPinDirection(DIO_PORTB,PIN3,OUTPUT);
#endif
}

void TIMER0_fastPWM(uint8 copy_compare_num)
{
	/* Wave Generation */
	SET_BIT(TCCR0,TCCR_WGM00);
	SET_BIT(TCCR0,TCCR_WGM01);

	CLEAR_BIT(TCCR0,TCCR_FOC0);

#if (TIMER0_COMPARE_MATCH_MODE_F_PWM == TIMER0_COMP_NORMAL_F_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM01);
	CLEAR_BIT(TCCR0,TCCR_COM00);

#elif (TIMER0_COMPARE_MATCH_MODE_F_PWM == TIMER0_COMP_CLEAR_F_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_F_PWM == TIMER0_COMP_SET_F_PWM)
	SET_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#else
#error "WRONG CONFIGURATIONS !!"
#endif

	OCR0 = copy_compare_num;

	/* Pre-Scaling Configuration */
	TCCR0 &= 0b11111000;
	TCCR0 |= PRESCALING_8_MASK;

#if (TIMER0_COMPARE_MATCH_MODE_F_PWM != TIMER0_COMP_NORMAL_F_PWM)
	DIO_setPinDirection(DIO_PORTB,PIN3,OUTPUT);
#endif

}

void TIMER0_phaseCorrectPWM(uint8 copy_compare_num)
{
	/* Wave Generation */
	SET_BIT(TCCR0,TCCR_WGM00);
	CLEAR_BIT(TCCR0,TCCR_WGM01);
	CLEAR_BIT(TCCR0,TCCR_FOC0);
	/* COMPARE MODES */
#if (TIMER0_COMPARE_MATCH_MODE_PC_PWM == TIMER0_COMP_NORMAL_PC_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM01);
	CLEAR_BIT(TCCR0,TCCR_COM00);

#elif (TIMER0_COMPARE_MATCH_MODE_PC_PWM == TIMER0_COMP_CLEAR_PC_PWM)
	CLEAR_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#elif (TIMER0_COMPARE_MATCH_MODE_PC_PWM == TIMER0_COMP_SET_PC_PWM)
	SET_BIT(TCCR0,TCCR_COM00);
	SET_BIT(TCCR0,TCCR_COM01);

#else
#error "WRONG CONFIGURATIONS !!"
#endif

	OCR0 = copy_compare_num;
	/* Pre-Scaling Configuration */
	TCCR0 &= 0b11111000;
	TCCR0 |= PRESCALING_1024_MASK;

#if (TIMER0_COMPARE_MATCH_MODE_PC_PWM != TIMER0_COMP_NORMAL_PC_PWM)
	DIO_setPinDirection(DIO_PORTB,PIN3,OUTPUT);
#endif
}

void TIMER1_init(void)
{

	/* Operation Modes */
#if (TIMER1_WAVE_GEN_MODE == TIMER1_NORMAL)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_8BIT)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_9BIT)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_10BIT)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_CTC_OCR1A)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = 2000;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = 2000;
#endif

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_8BIT)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_9BIT)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_10BIT)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PFC_TOP_ICR1)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

	ICR1 = 2000;

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PFC_TOP_OCR1A)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = 2000;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = 2000;
#endif

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_ICR1)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

	ICR1 = 40000;
#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_OCR1A)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = 2000;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = 2000;
#endif


#elif (TIMER1_WAVE_GEN_MODE == TIMER1_CTC_ICR1)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

	ICR1 = 40000;
#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_ICR1)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

	ICR1 = ICR1_TIMER_1;
	OCR1A = 2560;
#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_OCR1A)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = 2000;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = 2000;
#endif

#else
#error "WRONG CONFIGURATION !!"
#endif

	/* COMPARE MODE */
#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)

#if ((TIMER1_WAVE_GEN_MODE == TIMER1_NORMAL) || (TIMER1_WAVE_GEN_MODE == TIMER1_CTC_OCR1A) || (TIMER1_WAVE_GEN_MODE == TIMER1_CTC_ICR1))

#if (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_NORMAL_NO_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_TOGGLE_NO_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_CLEAR_NO_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_SET_NO_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#endif

#elif ((TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_8BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_9BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_10BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_ICR1) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_OCR1A))

#if (TIMER1_COMPARE_MATCH_MODE_F_PWM_A == TIMER1_COMP_NORMAL_F_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_A == TIMER1_COMP_TOGGLE_F_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_A == TIMER1_COMP_CLEAR_ON_COMP_F_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_A == TIMER1_COMP_SET_ON_COMP_F_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#endif

#elif ((TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_8BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_9BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_10BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PFC_TOP_ICR1) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PFC_TOP_OCR1A) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_ICR1) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_OCR1A))

#if (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_A == TIMER1_COMP_NORMAL_FPC_PFC_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_A == TIMER1_COMP_TOGGLE_PC_PFC_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_A == TIMER1_COMP_CLEAR_ON_COMP_PC_PFC_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_A == TIMER1_COMP_SET_ON_COMP_PC_PFC_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#endif

#endif

#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)

#if ((TIMER1_WAVE_GEN_MODE == TIMER1_NORMAL) || (TIMER1_WAVE_GEN_MODE == TIMER1_CTC_OCR1A) || (TIMER1_WAVE_GEN_MODE == TIMER1_CTC_ICR1))

#if (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_NORMAL_NO_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_TOGGLE_NO_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_CLEAR_NO_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_SET_NO_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#endif

#elif ((TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_8BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_9BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_10BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_ICR1) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_OCR1A))

#if (TIMER1_COMPARE_MATCH_MODE_F_PWM_B == TIMER1_COMP_NORMAL_F_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);
#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_B == TIMER1_COMP_TOGGLE_F_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_B == TIMER1_COMP_CLEAR_ON_COMP_F_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_B == TIMER1_COMP_SET_ON_COMP_F_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#endif

#elif ((TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_8BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_9BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_10BIT) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PFC_TOP_ICR1) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PFC_TOP_OCR1A) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_ICR1) || (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_OCR1A))

#if (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_B == TIMER1_COMP_NORMAL_FPC_PFC_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_B == TIMER1_COMP_TOGGLE_PC_PFC_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_B == TIMER1_COMP_CLEAR_ON_COMP_PC_PFC_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_B == TIMER1_COMP_SET_ON_COMP_PC_PFC_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#endif

#endif

#endif

	/* PRESCALING */
	TCCR1B &= 11111000;
	TCCR1B |= CLOCK_CYCLE_SELECTED;

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	DIO_setPinDirection(DIO_PORTD,PIN5,OUTPUT);
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	DIO_setPinDirection(DIO_PORTD,PIN4,OUTPUT);
#endif


	//OCR1A = 3000;


}

void TIMER1_normal(void)
{
	/*	Wave Generation Configuration	*/
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);


	/*	COMPARE MODE */
#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)



#if (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_NORMAL_NO_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_TOGGLE_NO_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_CLEAR_NO_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_SET_NO_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#endif

#endif


#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)


#if (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_NORMAL_NO_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_TOGGLE_NO_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_CLEAR_NO_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_SET_NO_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#endif

#endif

	/* PRESCALING */
	TCCR1B &= 11111000;
	TCCR1B |= CLOCK_CYCLE_SELECTED;

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	DIO_setPinDirection(DIO_PORTD,PIN5,OUTPUT);
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	DIO_setPinDirection(DIO_PORTD,PIN4,OUTPUT);
#endif

}

void TIMER1_CTC(uint16 copy_upper_limit)
{
	/*	Wave Generation Configuration	*/
#if (TIMER1_WAVE_GEN_MODE == TIMER1_CTC_ICR1)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

	ICR1 = copy_upper_limit;

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_CTC_OCR1A)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);


#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = copy_upper_limit;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = copy_upper_limit;
#endif

#else
//#error "WRONG CONFIGURATION !!"
#endif


	/*	COMPARE MODE */
#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)


#if (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_NORMAL_NO_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_TOGGLE_NO_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_CLEAR_NO_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_A == TIMER1_COMP_SET_NO_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#endif


#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)

#if (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_NORMAL_NO_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_TOGGLE_NO_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_CLEAR_NO_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_NO_PWM_B == TIMER1_COMP_SET_NO_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#endif

#endif


	/* PRESCALING */
	TCCR1B &= 11111000;
	TCCR1B |= CLOCK_CYCLE_SELECTED;

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	DIO_setPinDirection(DIO_PORTD,PIN5,OUTPUT);
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	DIO_setPinDirection(DIO_PORTD,PIN4,OUTPUT);
#endif

}

void TIMER1_fastPWM(void)
{
	/* Wave Generation Mode */
#if (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_8BIT)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_9BIT)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_10BIT)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_ICR1)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

	ICR1 = ICR1_TIMER_1;
#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = 2000;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = 2000;
#endif

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_F_OCR1A)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = 2000;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = 2000;
#endif

#else
#error "WRONG CONFIGURATION !!"
#endif

	/* Compare Mode */
#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)


#if (TIMER1_COMPARE_MATCH_MODE_F_PWM_A == TIMER1_COMP_NORMAL_F_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_A == TIMER1_COMP_TOGGLE_F_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_A == TIMER1_COMP_CLEAR_ON_COMP_F_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_A == TIMER1_COMP_SET_ON_COMP_F_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#endif
#endif



#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)

#if (TIMER1_COMPARE_MATCH_MODE_F_PWM_B == TIMER1_COMP_NORMAL_F_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_B == TIMER1_COMP_TOGGLE_F_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_B == TIMER1_COMP_CLEAR_ON_COMP_F_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1B0);

#elif (TIMER1_COMPARE_MATCH_MODE_F_PWM_B == TIMER1_COMP_SET_ON_COMP_F_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1B1);
	SET_BIT(TCCR1A,TCCR1A_COM1B0);

#endif
#endif

	/* PRESCALING */
	TCCR1B &= 11111000;
	TCCR1B |= CLOCK_CYCLE_SELECTED;

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	DIO_setPinDirection(DIO_PORTD,PIN5,OUTPUT);
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	DIO_setPinDirection(DIO_PORTD,PIN4,OUTPUT);
#endif

}

void TIMER1_phaseCorrectPWM(void)
{
	/* Wave Generation Mode */
#if (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_8BIT)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_9BIT)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_10BIT)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM13);

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PFC_TOP_ICR1)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

	ICR1 = 2000;

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = 2000;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = 2000;
#endif

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PFC_TOP_OCR1A)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	CLEAR_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = 2000;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = 2000;
#endif

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_ICR1)
	CLEAR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

	ICR1 = 40000;

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = 2000;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = 2000;
#endif

#elif (TIMER1_WAVE_GEN_MODE == TIMER1_PWM_PC_OCR1A)
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLEAR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	OCR1A = 2000;
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	OCR1B = 2000;

#endif
#endif

	/* compare mode */
#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)

#if (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_A == TIMER1_COMP_NORMAL_FPC_PFC_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_A == TIMER1_COMP_TOGGLE_PC_PFC_PWM_A)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_A == TIMER1_COMP_CLEAR_ON_COMP_PC_PFC_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_A == TIMER1_COMP_SET_ON_COMP_PC_PFC_PWM_A)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#endif

#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)

#if (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_B == TIMER1_COMP_NORMAL_FPC_PFC_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_B == TIMER1_COMP_TOGGLE_PC_PFC_PWM_B)
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_B == TIMER1_COMP_CLEAR_ON_COMP_PC_PFC_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	CLEAR_BIT(TCCR1A,TCCR1A_COM1A0);

#elif (TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_B == TIMER1_COMP_SET_ON_COMP_PC_PFC_PWM_B)
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	SET_BIT(TCCR1A,TCCR1A_COM1A0);

#endif

#endif


	/* PRESCALING */
	TCCR1B &= 11111000;
	TCCR1B |= CLOCK_CYCLE_SELECTED;

#if (CHANNEL_A_STATUS == CHANNEL_ENABLED)
	DIO_setPinDirection(DIO_PORTD,PIN5,OUTPUT);
#endif

#if (CHANNEL_B_STATUS == CHANNEL_ENABLED)
	DIO_setPinDirection(DIO_PORTD,PIN4,OUTPUT);
#endif

}

void TIMER2_init(void)
{
	/* Wave Generation Modes */
#if (TIMER2_WAVE_GEN_MODE == TIMER2_NORMAL)
	CLEAR_BIT(TCCR2,TCCR2_WGM20);
	CLEAR_BIT(TCCR2,TCCR2_WGM21);

#elif (TIMER2_WAVE_GEN_MODE == TIMER2_CTC)
	CLEAR_BIT(TCCR2,TCCR2_WGM20);
	SET_BIT(TCCR2,TCCR2_WGM21);

	OCR2 = 200;

#elif (TIMER2_WAVE_GEN_MODE == TIMER2_PWN_FAST)
	SET_BIT(TCCR2,TCCR2_WGM20);
	SET_BIT(TCCR2,TCCR2_WGM21);
	OCR2 = 200;

#elif (TIMER2_WAVE_GEN_MODE == TIMER2_PWM_PC)
	SET_BIT(TCCR2,TCCR2_WGM20);
	CLEAR_BIT(TCCR2,TCCR2_WGM21);
	OCR2 = 200;
#else
#error "WRONG CONFIGURATION !!"
#endif

#if ((TIMER2_WAVE_GEN_MODE == TIMER2_NORMAL) || (TIMER2_WAVE_GEN_MODE == TIMER2_CTC))

#if (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_NORMAL_NO_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM21);
	CLEAR_BIT(TCCR2,TCCR2_COM20);

#elif (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_TOGGLE_NO_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM21);
	SET_BIT(TCCR2,TCCR2_COM20);
#elif (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_CLEAR_NO_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#elif (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_SET_NO_PWM)
	SET_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#else
#error "WRONG CONFIGURATIONS !!"
#endif

#elif (TIMER2_WAVE_GEN_MODE == TIMER2_PWN_FAST)

#if (TIMER2_COMPARE_MATCH_MODE_F_PWM == TIMER2_COMP_NORMAL_F_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM21);
	CLEAR_BIT(TCCR2,TCCR2_COM20);

#elif (TIMER2_COMPARE_MATCH_MODE_F_PWM == TIMER2_COMP_CLEAR_F_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#elif (TIMER2_COMPARE_MATCH_MODE_F_PWM == TIMER2_COMP_SET_F_PWM)
	SET_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#else
#error "WRONG CONFIGURATIONS !!"
#endif

#endif

#if ((TIMER2_COMPARE_MATCH_MODE_NO_PWM != TIMER2_COMPARE_MATCH_MODE_NO_PWM) || (TIMER2_COMPARE_MATCH_MODE_F_PWM == TIMER2_COMPARE_MATCH_MODE_F_PWM) || (TIMER2_COMPARE_MATCH_MODE_PC_PWM == TIMER2_COMPARE_MATCH_MODE_PC_PWM))
	DIO_setPinDirection(DIO_PORTD,PIN7,OUTPUT);
#endif
}

void TIMER2_normal(void)
{
	/* Wave Generation */
	CLEAR_BIT(TCCR2,TCCR2_WGM20);
	CLEAR_BIT(TCCR2,TCCR2_WGM21);

#if (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_NORMAL_NO_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM21);
	CLEAR_BIT(TCCR2,TCCR2_COM20);

#elif (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_TOGGLE_NO_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM21);
	SET_BIT(TCCR2,TCCR2_COM20);
#elif (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_CLEAR_NO_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#elif (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_SET_NO_PWM)
	SET_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#else
#error "WRONG CONFIGURATIONS !!"
#endif

	/* Pre-Scaling Configuration */
	TCCR2 &= 0b11111000;
	TCCR2 |= TIMER2_PRESCALING_64_MASK;

#if (TIMER2_COMPARE_MATCH_MODE_NO_PWM != TIMER2_COMPARE_MATCH_MODE_NO_PWM)
	DIO_setPinDirection(DIO_PORTD,PIN7,OUTPUT);
#endif
}

void TIMER2_CTC_(uint8 copy_upper_limit)
{
	/* Wave Generation */
	CLEAR_BIT(TCCR2,TCCR2_WGM20);
	SET_BIT(TCCR2,TCCR2_WGM21);
	OCR2 = copy_upper_limit;

#if (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMPARE_MATCH_MODE_NO_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM21);
	CLEAR_BIT(TCCR2,TCCR2_COM20);

#elif (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_TOGGLE_NO_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM21);
	SET_BIT(TCCR2,TCCR2_COM20);

#elif (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_CLEAR_NO_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#elif (TIMER2_COMPARE_MATCH_MODE_NO_PWM == TIMER2_COMP_SET_NO_PWM)
	SET_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#else
#error "WRONG CONFIGURATIONS !!"
#endif

	/* Pre-Scaling Configuration */
	TCCR2 &= 0b11111000;
	TCCR2 |= TIMER2_PRESCALING_64_MASK;

#if (TIMER2_COMPARE_MATCH_MODE_NO_PWM != TIMER2_COMPARE_MATCH_MODE_NO_PWM)
	DIO_setPinDirection(DIO_PORTD,PIN7,OUTPUT);
#endif
}

void TIMER2_fastPWM(uint8 copy_compare_num)
{
	/* Wave Generation */
	SET_BIT(TCCR2,TCCR2_WGM20);
	SET_BIT(TCCR2,TCCR2_WGM21);

#if (TIMER2_COMPARE_MATCH_MODE_F_PWM == TIMER2_COMP_NORMAL_F_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM21);
	CLEAR_BIT(TCCR2,TCCR2_COM20);

#elif (TIMER2_COMPARE_MATCH_MODE_F_PWM == TIMER2_COMP_CLEAR_F_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#elif (TIMER2_COMPARE_MATCH_MODE_F_PWM == TIMER2_COMP_SET_F_PWM)
	SET_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#else
#error "WRONG CONFIGURATIONS !!"
#endif

	OCR2 = copy_compare_num;

	/* Pre-Scaling Configuration */
	TCCR2 &= 0b11111000;
	TCCR2 |= TIMER2_PRESCALING_1024_MASK;

#if (TIMER2_COMPARE_MATCH_MODE_F_PWM != TIMER2_COMP_NORMAL_F_PWM)
	DIO_setPinDirection(DIO_PORTD,PIN7,OUTPUT);
#endif

}

void TIMER2_phaseCorrectPWM(uint8 copy_compare_num)
{
	/* Wave Generation */
	SET_BIT(TCCR2,TCCR2_WGM20);
	CLEAR_BIT(TCCR2,TCCR2_WGM21);

	/* COMPARE MODES */
#if (TIMER2_COMPARE_MATCH_MODE_PC_PWM == TIMER2_COMP_NORMAL_PC_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM21);
	CLEAR_BIT(TCCR2,TCCR2_COM20);

#elif (TIMER2_COMPARE_MATCH_MODE_PC_PWM == TIMER2_COMP_CLEAR_PC_PWM)
	CLEAR_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#elif (TIMER2_COMPARE_MATCH_MODE_PC_PWM == TIMER2_COMP_SET_PC_PWM)
	SET_BIT(TCCR2,TCCR2_COM20);
	SET_BIT(TCCR2,TCCR2_COM21);

#else
#error "WRONG CONFIGURATIONS !!"
#endif

	OCR2 = copy_compare_num;
	/* Pre-Scaling Configuration */
	TCCR2 &= 0b11111000;
	TCCR2 |= TIMER2_PRESCALING_64_MASK;

#if (TIMER2_COMPARE_MATCH_MODE_PC_PWM != TIMER2_COMP_NORMAL_PC_PWM)
	DIO_setPinDirection(DIO_PORTD,PIN7,OUTPUT);
#endif
}

void TIMER0_turnOFF(void)
{
	TCCR0 &= 0b11111000;
}
void TIMER1_turnOFF(void)
{
	TCCR1B &= 11111000;
}
void TIMER2_turnOFF(void)
{
	TCCR2 &= 0b11111000;
}

void Delay_ms(uint32 time)
{
	uint32 local_ticks = 0;
	uint32 local_map = (time * 1000 * 16) / (OCR_TICK_NUMS  * PRESCALING_VALUE);
	while (local_ticks < local_map)
	{
		while (!(GET_BIT(TIFR,TIFR_TOV0)));
		(SET_BIT(TIFR,TIFR_TOV0));
		local_ticks++;
	}


}
