/*
 * Author   : Ahmed Mohamed Aboud
 * Linkedin :https://www.linkedin.com/in/ahmed-mohamed-aboud-33b2471b1/
 * File Name: TIMER_CFG.h
 * Date: 29 Dec 2023
 */

#ifndef TIMER_CFG_H_
#define TIMER_CFG_H_

/* TIMER 0 : Waveform Generation Mode */
#define TIMER0_NORMAL	1
#define TIMER0_CTC		2
#define TIMER0_PWN_FAST	3
#define TIMER0_PWM_PC	4

#define TIMER0_WAVE_GEN_MODE	TIMER0_PWN_FAST

/*  TIMER 0 : Compare Match Output Mode no PWM */
#define TIMER0_COMP_NORMAL_NO_PWM	1
#define TIMER0_COMP_TOGGLE_NO_PWM	2
#define TIMER0_COMP_CLEAR_NO_PWM	3
#define TIMER0_COMP_SET_NO_PWM		4

#define TIMER0_COMPARE_MATCH_MODE_NO_PWM	TIMER0_COMP_TOGGLE_NO_PWM

/*  TIMER 0 : Compare Match Output Mode FAST PWM */
#define TIMER0_COMP_NORMAL_F_PWM	1
#define TIMER0_COMP_CLEAR_F_PWM		2
#define TIMER0_COMP_SET_F_PWM		3

#define TIMER0_COMPARE_MATCH_MODE_F_PWM	TIMER0_COMP_CLEAR_F_PWM

/*  TIMER 0 : Compare Match Output Mode PC PWM */
#define TIMER0_COMP_NORMAL_PC_PWM	1
#define TIMER0_COMP_CLEAR_PC_PWM	2
#define TIMER0_COMP_SET_PC_PWM		3

#define TIMER0_COMPARE_MATCH_MODE_PC_PWM	TIMER0_COMP_SET_PC_PWM



/* TIMER 1 : Waveform Generation Mode */
#define TIMER1_NORMAL				1
#define TIMER1_PWM_PC_8BIT			2
#define TIMER1_PWM_PC_9BIT			3
#define TIMER1_PWM_PC_10BIT			4
#define TIMER1_CTC_OCR1A			5
#define TIMER1_PWM_F_8BIT			6
#define TIMER1_PWM_F_9BIT			7
#define TIMER1_PWM_F_10BIT			8
#define TIMER1_PWM_PFC_TOP_ICR1		9
#define TIMER1_PWM_PFC_TOP_OCR1A	10
#define TIMER1_PWM_PC_ICR1			11
#define TIMER1_PWM_PC_OCR1A			12
#define TIMER1_CTC_ICR1				13
#define TIMER1_PWM_F_ICR1			15
#define TIMER1_PWM_F_OCR1A			16

#define TIMER1_WAVE_GEN_MODE	TIMER1_PWM_F_ICR1

/*	TIMER 1 : Compare Match Output Mode no PWM */
#define TIMER1_COMP_NORMAL_NO_PWM_A		1
#define TIMER1_COMP_TOGGLE_NO_PWM_A		2
#define TIMER1_COMP_CLEAR_NO_PWM_A		3
#define TIMER1_COMP_SET_NO_PWM_A		4

#define TIMER1_COMP_NORMAL_NO_PWM_B		1
#define TIMER1_COMP_TOGGLE_NO_PWM_B		2
#define TIMER1_COMP_CLEAR_NO_PWM_B		3
#define TIMER1_COMP_SET_NO_PWM_B		4

#define TIMER1_COMPARE_MATCH_MODE_NO_PWM_A 		TIMER1_COMP_NORMAL_NO_PWM_A
#define TIMER1_COMPARE_MATCH_MODE_NO_PWM_B 		TIMER1_COMP_NORMAL_NO_PWM_B

/*  TIMER 1 : Compare Match Output Mode FAST PWM */
#define TIMER1_COMP_NORMAL_F_PWM_A				1
#define TIMER1_COMP_TOGGLE_F_PWM_A				2
#define TIMER1_COMP_CLEAR_ON_COMP_F_PWM_A		3
#define TIMER1_COMP_SET_ON_COMP_F_PWM_A			4

#define TIMER1_COMP_NORMAL_F_PWM_B				1
#define TIMER1_COMP_TOGGLE_F_PWM_B				2
#define TIMER1_COMP_CLEAR_ON_COMP_F_PWM_B		3
#define TIMER1_COMP_SET_ON_COMP_F_PWM_B			4

#define TIMER1_COMPARE_MATCH_MODE_F_PWM_A 		TIMER1_COMP_CLEAR_ON_COMP_F_PWM_A
#define TIMER1_COMPARE_MATCH_MODE_F_PWM_B 		TIMER1_COMP_NORMAL_F_PWM_B

/*  TIMER 1 : Compare Match Output Mode PC / PFC PWM */
#define TIMER1_COMP_NORMAL_PC_PFC_PWM_A					1
#define TIMER1_COMP_TOGGLE_PC_PFC_PWM_A					2
#define TIMER1_COMP_CLEAR_ON_COMP_PC_PFC_PWM_A			3
#define TIMER1_COMP_SET_ON_COMP_PC_PFC_PWM_A			4

#define TIMER1_COMP_NORMAL_PC_PFC_PWM_B					1
#define TIMER1_COMP_TOGGLE_PC_PFC_PWM_B					2
#define TIMER1_COMP_CLEAR_ON_COMP_PC_PFC_PWM_B			3
#define TIMER1_COMP_SET_ON_COMP_PC_PFC_PWM_B			4

#define TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_A 		TIMER1_COMP_NORMAL_PC_PFC_PWM_A
#define TIMER1_COMPARE_MATCH_MODE_PC_PFC_PWM_B 		TIMER1_COMP_NORMAL_PC_PFC_PWM_B


/* SELECTED CHANNEL */
#define CHANNEL_ENABLED 	1
#define CHANNEL_DISABLED 	2

#define CHANNEL_A_STATUS	CHANNEL_ENABLED
#define CHANNEL_B_STATUS	CHANNEL_DISABLED

/* TIMER 2 : Waveform Generation Mode */
#define TIMER2_NORMAL	1
#define TIMER2_CTC		2
#define TIMER2_PWN_FAST	3
#define TIMER2_PWM_PC	4

#define TIMER2_WAVE_GEN_MODE	TIMER2_PWN_FAST

/*  TIMER 2 : Compare Match Output Mode no PWM */
#define TIMER2_COMP_NORMAL_NO_PWM	1
#define TIMER2_COMP_TOGGLE_NO_PWM	2
#define TIMER2_COMP_CLEAR_NO_PWM	3
#define TIMER2_COMP_SET_NO_PWM		4

#define TIMER2_COMPARE_MATCH_MODE_NO_PWM	TIMER2_COMP_TOGGLE_NO_PWM

/*  TIMER 2 : Compare Match Output Mode FAST PWM */
#define TIMER2_COMP_NORMAL_F_PWM	1
#define TIMER2_COMP_CLEAR_F_PWM		2
#define TIMER2_COMP_SET_F_PWM		3

#define TIMER2_COMPARE_MATCH_MODE_F_PWM	TIMER2_COMP_CLEAR_F_PWM

/*  TIMER 2 : Compare Match Output Mode PC PWM */
#define TIMER2_COMP_NORMAL_PC_PWM	1
#define TIMER2_COMP_CLEAR_PC_PWM	2
#define TIMER2_COMP_SET_PC_PWM		3

#define TIMER2_COMPARE_MATCH_MODE_PC_PWM	TIMER2_COMP_SET_PC_PWM


/*  Clock Cycle TIMER 0/1 */
#define NO_CLOCK_SOURCE_MASK	0x00
#define NO_PRESCALING_MASK		0x01
#define PRESCALING_8_MASK		0x02
#define PRESCALING_64_MASK		0x03
#define PRESCALING_256_MASK		0x04
#define PRESCALING_1024_MASK	0x05
#define EXT_CLK_FALLING_MASK	0X06
#define EXT_CLK_RISING_MASK		0X07

#define CLOCK_CYCLE_SELECTED	 PRESCALING_1024_MASK

#define OCR_TICK_NUMS	200
#define OCR_COMP_VALUE	127

#define ICR1_TIMER_1	40000

/* Clock Cycle TIMER 2 */
#define TIMER2_NO_CLOCK_SOURCE_MASK		0x00
#define TIMER2_NO_PRESCALING_MASK		0x01
#define TIMER2_PRESCALING_8_MASK		0x02
#define TIMER2_PRESCALING_32_MASK		0x03
#define TIMER2_PRESCALING_64_MASK		0x04
#define TIMER2_PRESCALING_128_MASK		0x05
#define TIMER2_PRESCALING_256_MASK		0X06
#define TIMER2_PRESCALING_1024_MASK		0X07

#define TIMER2_CLOCK_CYCLE_SELECTED	 TIMER2_PRESCALING_1024_MASK

/* PRE-SCALING VALUES TIMER0/1 */

#define PRESCALING_1	1
#define PRESCALING_8	8
#define PRESCALING_64	64
#define PRESCALING_256	256
#define PRESCALING_1024	1024

#define PRESCALING_VALUE	PRESCALING_8

/* PRE-SCALING VALUES TIMER2 */

#define TIMER2_PRESCALING_1		1
#define TIMER2_PRESCALING_8		8
#define TIMER2_PRESCALING_32	32
#define TIMER2_PRESCALING_64	64
#define TIMER2_PRESCALING_128	128
#define TIMER2_PRESCALING_256	256
#define TIMER2_PRESCALING_1024	1024

#define TIMER2_PRESCALING_VALUE	TIMER2_PRESCALING_64

#endif /* TIMER_CFG_H_ */
